-- Migration: Add UI Schema support to briefings table
-- Purpose: Enable dynamic UI generation for briefings via A2UI system
-- Date: 2026-01-16

-- Add ui_schema field to store dynamic UI configuration
ALTER TABLE briefings
ADD COLUMN IF NOT EXISTS ui_schema JSONB;

-- Add Schema version field
ALTER TABLE briefings
ADD COLUMN IF NOT EXISTS ui_schema_version VARCHAR(10) DEFAULT '1.0';

-- Add index for ui_schema type queries
CREATE INDEX IF NOT EXISTS idx_briefings_ui_schema_type
ON briefings ((ui_schema->>'type'));

-- Add comment for documentation
COMMENT ON COLUMN briefings.ui_schema IS 'Dynamic UI schema generated by AI for adaptive component rendering';
COMMENT ON COLUMN briefings.ui_schema_version IS 'Version of UI schema format for compatibility tracking';
